pipeline {
  agent any

  parameters {
    string description: 'Enter email address', name: 'EMAIL_ADDRESS'
  }

  stages {
    stage('Send Email') {
      steps {
        echo "sending email to ${params.EMAIL_ADDRESS}"
        mail body: 'testing', subject: 'testing OrangeHRM', to: "${params.EMAIL_ADDRESS}"
      }
    }
    
    stage('Checkout') {
      steps {
                script {
                    checkout scmGit(
                        branches: [[name: '*/test_branch2']],
                        extensions: [
                            sparseCheckout([
                                [path: 'src'],
                                [path: 'pom.xml'],
                                [path: 'testng.xml']
                            ])
                        ],
                        userRemoteConfigs: [[url: 'https://github.com/vaibhavjain0007/OrangeHRM']]
                    )
                }
            }
    }

    stage ('Test') {
      steps {
        bat 'mvn clean test'
      }
    }
  }

  post {
    always {
      // Archive HTML report (adjust the path to where your report is generated)
      publishHTML([ 
        reportName: 'Test Report',
        reportDir: 'target/test-output', // This should be where your HTML report is generated
        reportFiles: 'index.html', // Name of the report file generated by your tests
        keepAll: true
      ])
    }
  }
}
